### PR TITLE
Update fuzion-civicrm-4.7.24.1-drupal7.make

### PR DESCRIPTION
**Pull request by jitendrapurohit**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Hmm you'd better self-merge to this repo since I don't know who would know better than you without Chris around

**Comment by jitendrapurohit** [comment]
Thanks @eileenmcnaughton. Maybe, I need to ask Pete to provide merge access on this repo.

**Comment by eileenmcnaughton** [comment]
Are you sure you don't have it - the config looks like you do

**Comment by jitendrapurohit** [comment]
I got it some hours before by Pete. Thanks 👍

**Pull request merged**
